[Unit]
Description=Temporary Directory (/tmp) — capped for low-resource hosts
Documentation=man:tmpfs(5)
Before=local-fs.target
After=swap.target

[Mount]
What=tmpfs
Where=/tmp
Type=tmpfs
Options=mode=1777,strictatime,nosuid,nodev,size=10%,nr_inodes=500k

[Install]
WantedBy=local-fs.target
